/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Vitor
 */
public class Calculadora_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora_GUI
     */
    public Calculadora_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        n2 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        LIMPA = new javax.swing.JButton();
        DIV = new javax.swing.JButton();
        SUB = new javax.swing.JButton();
        SOMA = new javax.swing.JButton();
        MULT = new javax.swing.JButton();
        FECHAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RESU = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setLayout(null);

        n2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        n2.setForeground(new java.awt.Color(255, 162, 219));
        jPanel1.add(n2);
        n2.setBounds(130, 60, 130, 40);

        n1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        n1.setForeground(new java.awt.Color(255, 162, 219));
        jPanel1.add(n1);
        n1.setBounds(130, 10, 130, 40);

        LIMPA.setBackground(new java.awt.Color(255, 162, 219));
        LIMPA.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        LIMPA.setText("C");
        LIMPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPA);
        LIMPA.setBounds(290, 130, 70, 70);

        DIV.setBackground(new java.awt.Color(255, 255, 255));
        DIV.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        DIV.setForeground(new java.awt.Color(255, 102, 204));
        DIV.setText("/");
        DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVActionPerformed(evt);
            }
        });
        jPanel1.add(DIV);
        DIV.setBounds(10, 120, 120, 40);

        SUB.setBackground(new java.awt.Color(255, 255, 255));
        SUB.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        SUB.setForeground(new java.awt.Color(255, 102, 204));
        SUB.setText("-");
        SUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBActionPerformed(evt);
            }
        });
        jPanel1.add(SUB);
        SUB.setBounds(10, 170, 120, 40);

        SOMA.setBackground(new java.awt.Color(255, 255, 255));
        SOMA.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        SOMA.setForeground(new java.awt.Color(255, 102, 204));
        SOMA.setText("+");
        SOMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOMAActionPerformed(evt);
            }
        });
        jPanel1.add(SOMA);
        SOMA.setBounds(140, 170, 120, 40);

        MULT.setBackground(new java.awt.Color(255, 255, 255));
        MULT.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        MULT.setForeground(new java.awt.Color(255, 102, 204));
        MULT.setText("*");
        MULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTActionPerformed(evt);
            }
        });
        jPanel1.add(MULT);
        MULT.setBounds(140, 120, 120, 40);

        FECHAR.setBackground(new java.awt.Color(255, 162, 219));
        FECHAR.setFont(new java.awt.Font("Lato", 1, 8)); // NOI18N
        FECHAR.setText("X");
        FECHAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FECHARActionPerformed(evt);
            }
        });
        jPanel1.add(FECHAR);
        FECHAR.setBounds(300, 10, 50, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("2º número ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 110, 40);

        RESU.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        RESU.setForeground(new java.awt.Color(255, 162, 219));
        jPanel1.add(RESU);
        RESU.setBounds(10, 230, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setText("=");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 230, 30, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel4.setText("1º número ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/hello_kitty.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 370, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 280);

        setSize(new java.awt.Dimension(370, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FECHARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FECHARActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FECHARActionPerformed

    private void SOMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOMAActionPerformed
        Model.Calcular_DAO.soma();
    }//GEN-LAST:event_SOMAActionPerformed

    private void DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVActionPerformed
        Model.Calcular_DAO.divisao();
    }//GEN-LAST:event_DIVActionPerformed

    private void MULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTActionPerformed
        Model.Calcular_DAO.multi();
    }//GEN-LAST:event_MULTActionPerformed

    private void SUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBActionPerformed
        Model.Calcular_DAO.subtracao();
    }//GEN-LAST:event_SUBActionPerformed

    private void LIMPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAActionPerformed
        Model.Calcular_DAO.limpa();
    }//GEN-LAST:event_LIMPAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton DIV;
    public static javax.swing.JButton FECHAR;
    public static javax.swing.JButton LIMPA;
    public static javax.swing.JButton MULT;
    public static javax.swing.JTextField RESU;
    public static javax.swing.JButton SOMA;
    public static javax.swing.JButton SUB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField n1;
    public static javax.swing.JTextField n2;
    // End of variables declaration//GEN-END:variables
}
